version: '3.8'

services:
  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/order_book
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://order_book:rekwde4234rekNJrewfwef@13.49.223.194:5432/order_book"
    depends_on:
      - wait_for_db

  wait_for_db:
    image: busybox
    command: sh -c "until nc -z 13.49.223.194 5432; do echo 'Waiting for PostgreSQL...'; sleep 2; done;"